import { StyleSheet, Platform } from 'react-native';

const style = StyleSheet.create({
    fondo:{
        flex:1,
        justifyContent:'center',
        backgroundColor:'#fff'
    },
    containers:{
        flex: 1,
        justifyContent: "space-around"
    },
    logo:{
        width:160,
        height:65,
        alignSelf:'center',
    },
    container:{
        alignItems:'center',
        justifyContent:'center'
    },
    input:{
        padding:12,
        borderColor:'#e8e8e8',
        borderWidth:2,
        borderRadius:8,
        margin:4,
        width:'75%',
        fontSize:18,
        fontFamily:'Proxima',
        marginBottom:5
    },
    btnPrimary:{
        margin:2,
        padding:5,
        backgroundColor:'#7145d6',
        width:'75%',
        height:50,
        borderRadius:10,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    Miembro:{
        padding:5,
        //backgroundColor:'#7145d6',
        width:'100%',
        height:50,
        borderRadius:10,
        flexDirection:'row',
        //justifyContent:'center',
        //alignItems:'center'
    },
    btnPrimaryOutline:{
        margin:2,
        padding:5,
        borderColor:'#7145d6',
        borderWidth:1.5,
        width:'75%',
        height:50,
        borderRadius:10,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    btnPrimaryOutlineText:{
        fontFamily:'ProximaBold',
        fontSize:18,
        textAlign:'center',
        textAlignVertical:'center',
        color:'#7145d6',
    },
    PrimaryOutlineText:{
        marginTop:4,
        fontFamily:'Proxima',
        fontSize:18,
        textAlign:'center',
        textAlignVertical:'center',
        color:'#7145d6',
    },
    btnPrimaryText:{
        fontFamily:'ProximaBold',
        fontSize:18,
        textAlign:'center',
        textAlignVertical:'center',
        color:'#fff',
    },
    PrimaryText:{
        fontFamily:'ProximaBold',
        fontSize:32,
        color:'#191414'
    },
    NormalText:{
        fontFamily:'Proxima',
        fontSize:21
    },
    btnWelcome:{
        margin:2,
        padding:5,
        backgroundColor:'#7145d6',
        width:'100%',
        height:62,
        borderRadius:10,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    btnWelcomeText:{
        fontFamily:'ProximaBold',
        fontSize:18,
        textAlign:'center',
        textAlignVertical:'center',
        color:'#fff',
    },
    headText:{
        fontFamily:'ProximaBold',
        color:'#fff',
        fontSize:23
    },
});

export { style };